project_name: Remote
before:
  hooks:
    - go mod tidy
builds:
  - id: remote-win
    ldflags: "-s -w -H=windowsgui"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
  - id: remote-linux
    ldflags: "-s -w"
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: "{{ tolower .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksum.txt'